### ISSUE TITLE
Can't able to hide/show buttons programatically

### ISSUE THREAD

**Issue by vinodkumar526** [maiyaporn/angular2-wizard-demo#1]
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-seller-registration',
  templateUrl: './seller-registration.component.html',
  styleUrls: ['./seller-registration.component.css']
})
export class SellerRegistrationComponent implements OnInit {
  step1Prev:boolean = false;
  constructor() { 
    
  }

  ngOnInit() {
  } 
  step2: any = {
    showNext: true,
    showPrev: true
  };

  step3: any = {
    showSecret: false
  };

  data: any = {
    email: 'muk@gmail.com'
  };

  isCompleted: boolean = false;

  onStep1Next(event) {
    console.log('Step1 - Next');
  }

  onStep2Next(event) {
    console.log('Step2 - Next');
  }

  onStep3Next(event) {
    console.log('Step3 - Next');
  }

  onComplete(event) {
    this.isCompleted = true;
  }

  onStepChanged(step) {
    console.log('Changed to ' + step.title);
  }
}

`<div class="container-fluid col-md-12">
    <div class="reg-header-left">
        <img class="header-logo"src="assets/img/Logo.png"/>
    </div>
</div>
<div class="container">
    <section class="demo">
      <h1>
        Angular5 - Form Wizard Demo
      </h1>
      <hr/>
      <div style="height: 350px;">
      <form-wizard (onStepChanged)="onStepChanged($event)">
        <wizard-step [showPrev]="step1Prev" [title]="'Step1'" [isValid]="emailForm.form.valid" (onNext)="onStep1Next($event)">
          <h1>Step1</h1>
          <p class="lead">Email is required to proceed to the next step.</p>
          <form #emailForm="ngForm">
            <div class="form-group">
              <label for="exampleInputEmail1">Email address</label>
              <input type="email" class="form-control" id="exampleInputEmail1" name="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email"
                [(ngModel)]="data.email" required>
              <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
          </form>
        </wizard-step>
        <wizard-step [title]="'Step2'" (onNext)="onStep2Next($event)">
          <h1>Step2</h1>
          <p class="lead">You can also control when to show/hide navigation buttons.</p>
          <form>
            <div class="form-check">
              <label class="form-check-label">
                <input type="checkbox" class="form-check-input" name="showNext" [(ngModel)]="step2.showNext"/>
                Show Next button
              </label>
            </div>
            <div class="form-check">
              <label class="form-check-label">
                <input type="checkbox" class="form-check-input" name="showPrev" [(ngModel)]="step2.showPrev"/>
                Show Previous button
              </label>
            </div>
          </form>
        </wizard-step>
        <wizard-step [title]="'Step3'" (onNext)="onStep3Next($event)">
          <h1>Step3</h1>
          <p class="lead">Check below if you want to access secret step</p>
          <form>
            <div class="form-check">
              <label class="form-check-label">
                <input type="checkbox" class="form-check-input" name="secret" [(ngModel)]="step3.showSecret"/>
                I want to know the secret
              </label>
            </div>
          </form>
        </wizard-step>
        <wizard-step [title]="'Step3.5'" [hidden]="!step3.showSecret">
          <h1>Step3.5</h1>
          <p class="lead">This is a secret place only special people can see this!!</p>
        </wizard-step>
       <wizard-step [title]="'Step4'" (onComplete)="onComplete($event)">
          <div [ngSwitch]="isCompleted">
            <div *ngSwitchDefault>
              <h1>Step4</h1>
              <p class="lead">This is the final step.</p>
            </div>
            <div *ngSwitchCase="true">
              <h4>Thank you {{data.email}}! You have completed all the steps.</h4>
            </div>
          </div>
        </wizard-step>
      </form-wizard>
      </div>
    </section>
  </div>`

**Comment by radiumrasheed** [comment]
hi @vinodkumar526 I'm curious to why you closed this ??
